[build]
  command = "npm install"
  publish = "public"  # Update this if your static files are in another folder (e.g., "build")

[functions]
  directory = "netlify-functions"  # Your serverless function folder

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/app/admin"  # Points to the serverless function for the /admin route
  status = 200
