[build]
  command = "npm install"  # or "npm run build" if you have a build process
  publish = "public"  # Static files location (adjust as needed)

[functions]
  directory = "netlify-functions"  # Ensure this folder exists for serverless functions
