[build]
  command = "npm install"  # Ensure dependencies are installed
  publish = "public"  # If you have a "public" folder for static files, else adjust

[functions]
  directory = "netlify-functions"  # Make sure this is where the serverless functions are located

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/app/admin"
  status = 200
