[build]
  command = "npm run build"  # Change to "npm install" if you don't have a separate build process
  publish = "public"  # Folder to store static files, like CSS, JS, and images

[functions]
  directory = "netlify-functions"  # This is where your serverless functions are located

[[redirects]]
  from = "/admin"
  to = "/admin"  # Handles the dynamic routing with the function
  status = 200  # Status 200 will allow the function to serve this route dynamically
