[build]
  functions = "netlify-functions"  # Make sure this points to your functions folder
  command = "npm run build"  # Or any custom build command

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/app/admin"  # Route to your function handling /admin
  status = 200
