[build]
  command = "npm run build"  # If you need a build process, otherwise just npm install
  publish = "public"  # If you have a static folder for assets

[functions]
  directory = "netlify-functions"  # Ensure serverless functions are in this folder
